### ISSUE TITLE
Throwing exceptions instead of returning Mono.error breaks the reactive chain.

### ISSUE THREAD

**Issue by kristo-godari** [aerospike-community/spring-data-aerospike#108]
You use org.springframework.util.Assert to validate different things.  Ex:
`
Assert.isTrue(expiration > 0, "Expiration value must be greater than zero, but was: " + expiration);
`
In my reactive code I have many .onErrorResume that should catch exceptions.  They work only if a Mono.error is triggered in the chain. Using the spring Assert will directly throw an exception and all my .onErrorResume are skipped and the exception is handled by spring default error handling.  Which is not what we want if you rely heavily to control the flow using .onError.. operators.

To fix this i need to do something like this in my reactive repository:
```	
default Mono<Document> saveWithErrorHandling(Document document){
	try {
		return save(document);
	}catch (Exception exception){
		return Mono.error(exception);
	}
}

```
You can do this try catch at the library level so we don't have to do it in our application. Or you can remove all the code that throws exceptions, and replace with Mono.error.

**Comment by Aloren** [comment]
These asserts should not be thrown in runtime on production. They are checks for developers that the passed parameters are valid. Why do you catch them? You need to fix the code so that it does not pass invalid data.

**Comment by kristo-godari** [comment]
You are missing the point here. The assert was just on example, there are also other exceptions that are thrown. This does not justify the fact that the library is not fully Reactive. 

In reactive we rely on operator like .onErrorResume, .onErrorReturn for the business flow, throwing Exceptions of any kind will bypass this operators and break the flow.

If we use Reactive we expect that the library complains with the Reactive standarts.
