### ISSUE TITLE
Handle TODO's

### ISSUE THREAD

**Issue by roimenashe** [aerospike-community/spring-data-aerospike#153]
Currently there are 33 TODO's in 26 Files.

**Comment by Aloren** [comment]
I would suggest splitting TODOs into different tasks as some of them are about minor cleanup of the code and others are about implementing unsupported features. Implementing all of them together will be a big mess.

**Comment by Aloren** [comment]
@roimenashe I think this one is already done and can be closed?

**Comment by roimenashe** [comment]
@Aloren We still have some TODO's in spring-data-aerospike, some are irrelevant now I guess but I think we should keep it for now and can always address it as a low priority task in case our backlog will get empty.
