### ISSUE TITLE
Storing a user key twice

### ISSUE THREAD

**Issue by roimenashe** [aerospike-community/spring-data-aerospike#154]
We store @user_key by default in Aerospike when using spring-data-aerospike.
In some scenarios we store the user key twice, for example:

1. "PK" bin sends via save() method when using AerospikeRepository (WritePolicyBuilder.sendkey = true in BaseAerospikeTemplate class).

2. "@user_key" bin is added in MappingAerospikeWriteConverter class (in all spring-data-aerospike operations).

Attached image that shows an example of storing the user key twice:
<img width="1058" alt="issue screenshot" src="https://user-images.githubusercontent.com/33356310/109796339-b4db4a00-7c20-11eb-9de3-eac9f6fe6433.png">

**Comment by Aloren** [comment]
We did it on purpose. `sendKey` property is disabled by default in the client and many users do not know about that property. So when historical data is already in storage on production, there is no ability to get the key of the record, that's why we decided to always write a key out of the box.

**Comment by roimenashe** [comment]
@Aloren I see, but there are scenarios that causes the key to be written twice ("PK" via sendKey and "@user_key" via mapping converter) without changing any property (same as I did without being aware of the sendKey property), is it normal behaviour? if someone uses save() method via the AerospikeRepository it will write the key twice (as two different bins).

**Comment by Aloren** [comment]
i think writing key twice can be fixed. why closed?)

**Comment by roimenashe** [comment]
Re-opened.

**Comment by roimenashe** [comment]
@Aloren @reugn 
**Update:** a PR for this issue is now open,
***Note:** PK is not a bin its stored as "userKey" in the Key object (this is done in the Aerospike Client side), after removing it all tests are passing and it looks like we don't use it in Spring Data Aerospike, @user_key on the other hand is used for conversion and as you mentioned storing the user-key might be useful for the user.

**Comment by roimenashe** [comment]
Fix will be included in the next version of spring-data-aerospike `3.1.0`.
PR: https://github.com/aerospike-community/spring-data-aerospike/pull/275
