### ISSUE TITLE
Evolved schema is not persisted to aerospike database

### ISSUE THREAD

**Issue by rajcspsg** [aerospike-community/spring-data-aerospike#163]
Hi,

I've below entity class - 

```
    package com.demo.aerospike.entity;

    import org.springframework.data.annotation.Id;
    import java.io.Serializable;
    import java.util.HashMap;

    public class User implements Serializable {

        @Id
        private String id;

        private HashMap<String, String> eUserIds = new HashMap();

        //getters/setters/toString/equals/hashCode
    }
```

Below is the repository class -

```
package com.demo.aerospike.repositories;

import com.demo.aerospike.entity.User;
import org.springframework.data.aerospike.repository.AerospikeRepository;

public interface UserRepository extends AerospikeRepository<User, String> {}
```

Below is spring application context -

```
package com.demo.aerospike.config;

import com.aerospike.client.AerospikeClient;
import com.aerospike.client.policy.ClientPolicy;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.aerospike.core.AerospikeTemplate;
import org.springframework.data.aerospike.repository.config.EnableAerospikeRepositories;

@Configuration
@EnableAerospikeRepositories(basePackages = "com.demo.aerospike.repositories")
public class AerospikeConfig {
    public @Bean(destroyMethod = "close") AerospikeClient aerospikeClient() {
        ClientPolicy policy = new ClientPolicy();
        policy.failIfNotConnected = true;
        String localhost = "localhost";
        return new AerospikeClient(policy, localhost, 3000);
    }

    public @Bean AerospikeTemplate aerospikeTemplate() {
        return new AerospikeTemplate(aerospikeClient(), "test");
    }
}

```

Below is my main class -

```
package com.demo.aerospike;

import com.demo.aerospike.config.AerospikeConfig;
import com.demo.aerospike.entity.User;
import com.demo.aerospike.repositories.UserRepository;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import java.util.*;

public class MySpringDataAerospikeDemo {

    public static void main(String []args) {

        ApplicationContext ctx = new AnnotationConfigApplicationContext(AerospikeConfig.class);
        UserRepository repository = ctx.getBean(UserRepository.class);
        HashMap<String, String> daveMap = new HashMap<>();
        daveMap.put(UUID.randomUUID().toString(), UUID.randomUUID().toString());
        User dave = new User("Dave-01", daveMap);
        repository.save(dave);
        Optional<User> davenew = repository.findById(dave.getId());
        System.out.println("new dave is \n" + davenew);
    }
}
```

All the above is working fine.
The issue comes when I am adding new field say `name` to User entity.

```
    package com.demo.aerospike.entity;

    import org.springframework.data.annotation.Id;
    import java.io.Serializable;
    import java.util.HashMap;

    public class User implements Serializable {

        @Id
        private String id;

        private String name;
        
        private HashMap<String, String> eUserIds = new HashMap();

        //getters/setters/toString/equals/hashCode
    }

```

The new main program is -

```

public class MySpringDataAerospikeDemo {

    public static void main(String []args) {

        ApplicationContext ctx = new AnnotationConfigApplicationContext(AerospikeConfig.class);
        UserRepository repository = ctx.getBean(UserRepository.class);
        HashMap<String, String> daveMap = new HashMap<>();
        daveMap.put(UUID.randomUUID().toString(), UUID.randomUUID().toString());
        User dave = new User("Dave-01", daveMap);
        dave.setName("Dave");
        repository.save(dave);
        Optional<User> davenew = repository.findById(dave.getId());
        System.out.println("new dave is \n" + davenew);
    }
}
```

the name field is not added to schema. only fields which are mentioned in V1 version of User are persisted.

I've found workaround But it would be good if it can work by default.

The workaround is run the below program to create new column in the set 

```
package com.demo.aerospike;

import com.aerospike.client.AerospikeClient;
import com.aerospike.client.Bin;
import com.aerospike.client.Key;
import com.aerospike.client.Record;
import java.util.Map;

public class AerospikeJavaDemo {

    public static void main(String[] args) {
        AerospikeClient client = new AerospikeClient("localhost", 3000);
        Key k1 = new Key("test", "User", "Dave-01");
        Record record = client.get(null, k1);
        Map<String, Object> bins = record.bins;
        bins.put("name", "Dave");
        System.out.println("record is "+ bins);
        int binSize = bins.size();
        System.out.println("binSize = " + binSize);
        Bin[] binArray =  bins.entrySet().stream().map(x -> new Bin(x.getKey(), x.getValue())).toArray(Bin[]::new);
        client.put(null, k1,binArray);
    }
}
```

Is there a way I can achieve schema evolution without any workaround seamlessly?

**Comment by roimenashe** [comment]
I tried to simulate your issue with a similar project (based on https://medium.com/aerospike-developer-blog/simple-web-application-using-java-spring-boot-aerospike-database-and-docker-ad13795e0089) I also changed a few things to even be more aligned (removed @Document annotation, added implements Serializable, implement AerospikeRepository instead of crudRepository and more...)

And this doesn't happen to me - schema evolution works.

**2 Things I would check:**
1. Do you have a getter on the new created field (name)? if not, I checked and this causes the issue you described - I would suspect this is the issue.
2. What version of spring-data-aerospike are you using? the new AerospikeTemplate(client, namespace) in the configuration class makes me think its not the latest version.

**Comment by rajcspsg** [comment]
@roimenashe 
Aerospike version is 

```
$ aql --version
Aerospike Query Client
Version 3.27.1
C Client Version 4.6.15
Copyright 2012-2020 Aerospike. All rights reserved.
```

Spring data aerospike version is 2.3.3.RELEASE

I have getters/setters on my newly created field.

**Comment by Aloren** [comment]
@rajcspsg please provide a minimal viable project which reproduces an issue. otherwise it is difficult to guess what is broken in the setup

**Comment by roimenashe** [comment]
It seems like a lot have changed since spring-data-aerospike 2.3.3.RELEASE.
Your way of configuring the beans is deprecated and also there are many changes in the AerospikeTemplate area.
Can you upgrade to Spring-data-aerospike 2.4.X?

**Comment by rajcspsg** [comment]
@roimenashe I'm trying to update my code before the spring-data-aerospike version to 2.4.2. 

The only change I'm doing to the existing code is creating AerospikeTemplate with additional parameters.

```
 public @Bean AerospikeTemplate aerospikeTemplate() {
        CustomConversions conversions = new CustomConversions(Collections.emptyList(), AerospikeSimpleTypes.HOLDER);
        AerospikeTypeAliasAccessor accessor = new AerospikeTypeAliasAccessor();
        MappingAerospikeConverter converter = new MappingAerospikeConverter(new AerospikeMappingContext(), conversions, accessor);
        AerospikeMappingContext context = new AerospikeMappingContext();
        context.setDefaultNameSpace("test");
        return  new AerospikeTemplate(aerospikeClient(), "test", converter, context, new AerospikeExceptionTranslator(){
            @Override
            public DataAccessException translateExceptionIfPossible(RuntimeException ex) {
                ex.printStackTrace();
                return new DataAccessException(ex.getMessage()) {
                };
            }
        });
        //return new AerospikeTemplate(aerospikeClient(), "test");
    }

```

When I run this code I get below exception.

>com.aerospike.client.AerospikeException$InvalidNamespace: Error 20: Namespace not found in partition map: null
>	at com.aerospike.client.cluster.Partition.write(Partition.java:36)
>	at com.aerospike.client.command.WriteCommand.<init>(WriteCommand.java:43)
>	at com.aerospike.client.AerospikeClient.put(AerospikeClient.java:384)
>	at org.springframework.data.aerospike.core.AerospikeTemplate.put(AerospikeTemplate.java:604)
>	at org.springframework.data.aerospike.core.AerospikeTemplate.doPersistAndHandleError(AerospikeTemplate.java:576)
>	at org.springframework.data.aerospike.core.AerospikeTemplate.save(AerospikeTemplate.java:179)
>	at org.springframework.data.aerospike.repository.support.SimpleAerospikeRepository.save(SimpleAerospikeRepository.java:55)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:498)
>	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
>	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
>	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
>	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
>	at com.sun.proxy.$Proxy25.save(Unknown Source)
>	at com.demo.aerospike.RunUpdatedClassDemo.main(RunUpdatedClassDemo.java:24)

If I use `return new AerospikeTemplate(aerospikeClient(), "test");` then it is working fine.
Any idea how can I fox this error?

**Comment by roimenashe** [comment]
@rajcspsg

On spring-data-aerospike 2.4.2 you don’t have to define AerospikeTemplate @bean, extending "AbstractAerospikeDataConfiguration" in your configuration class will provided it for you, all you have to do is to override getHosts() and nameSpace() methods. check out the configuration class on this demo [](https://medium.com/aerospike-developer-blog/simple-web-application-using-java-spring-boot-aerospike-database-and-docker-ad13795e0089)

**Comment by rajcspsg** [comment]
I can confirm that the issue doesn't exist in spring-data-aerospike version 2.4.2.RELEASE.
I'm closing the ticket. Thanks @roimenashe !!!
