### ISSUE TITLE
Feature: Support for Enums in Repository Functions

### ISSUE THREAD

**Issue by mikecaulley** [aerospike-community/spring-data-aerospike#166]
## Summary
I'd like to use Enums in Java code and have the values saved as Strings in Aerospike.  When creating new repository functions the  
AerospikeQueryCreator and Value classes should use the enum.toString() function to properly generate the query.

## Example
Given
```
@Repository
public interface UserRepository extends ReactiveAerospikeRepository<User, UUID> {

  Flux<User> findAllByStatus(Status status);
}
```

and

```
@AllArgsConstructor
public enum Status{
  ACTIVE,
  INACTIVE
}
```

and 

```
@Data
@Document(collection = "user")
@Builder
@AllArgsConstructor
public class User {
  @Id UUID id;

  @Indexed(type = IndexType.STRING)
  @Field
  Status status;
}
```

When calling the repository function `repository.findAllByStatus(Status.PENDING)` the generated query would be `select * from test.user where status="ACTIVE"`

**Comment by mikecaulley** [comment]
Closing in favor of the change in the client project.

https://github.com/aerospike/aerospike-client-java/issues/182

**Comment by Aloren** [comment]
@mikecaulley thanks for digging into the issue :)
