### ISSUE TITLE
upgrade to spring data pascal

### ISSUE THREAD

**Issue by Aloren** [aerospike-community/spring-data-aerospike#208]
https://spring.io/blog/2021/04/20/what-s-new-in-spring-data-2021-0

**Comment by Aloren** [comment]
in a separate major release, as update will contain non backward compatible changes

**Comment by roimenashe** [comment]
2.5.0 and 3.0.0 new major releases are using spring dependencies of 2.5.x (which are the versions of Spring Data 2021 AKA Pascal).
Also both versions now support deleteAllById() new operation both in reactive and non-reactive flows.
