### ISSUE TITLE
Using ClientPolicy of AerospikeClient object in AerospikeTemplate.findById method

### ISSUE THREAD

**Issue by mkamar01** [aerospike-community/spring-data-aerospike#260]
Hi,

Can you please advise why readPolicy is null when aerospikeClient.get method is executed from aerospikeTemplate ? Would like to get the readPolicy from clientpolicy and make the get request.

AerospikeTemplate Reference - 

https://github.com/aerospike-community/spring-data-aerospike/blob/4ce7f04d9dfd0ba50542090fc30ea768ad335403/src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java#L285

**Comment by Aloren** [comment]
Aerospike client uses default read policy assigned to the client, when null is passed.
