### ISSUE TITLE
com.aerospike.client.AerospikeException: Error 16,1,30000,0,5,BB9020011AC4202 172.17.0.2 3000: Unsupported Server Feature

### ISSUE THREAD

**Issue by vikas8910** [aerospike-community/spring-data-aerospike#281]
I am getting Unsupported Server Feature exception while getting data from aerospike. But insert and update and findById works fine for me.

Below are the snippets code for reference which gives me error. PLz help 

bankDetailsRepository.findAll();
bankDetailsRepository.findByCity("mumbai");
bankDetailsRepository.findByBankName(bankName));

**Comment by roimenashe** [comment]
@vikas8910 findAll(Class<T> entityClass) is supported, findAll(Sort sort, Class<T> entityClass) is not supported.
Regarding findByCity and findByBankName, they are both should be supported out-of-the-box using AerospikeRepository.

please share your code - repository, configuration, document object and also the versions you'r using, if you can add the entire project as a GitHub project I'll be happy to review it.

**Comment by reugn** [comment]
@vikas8910 please share your Aerospike cluster version and the library version you use.

**Comment by vikas8910** [comment]
> @vikas8910 please share your Aerospike cluster version and the library version you use.

**Comment by vikas8910** [comment]
> @vikas8910 please share your Aerospike cluster version and the library version you use.

I am using docker image of aerospike. Below are the details,

1) C Client Version 4.6.17

2) Aerospike Query Client Version 5.0.1

3) dependency in pom.xml
<dependency>
<groupId>com.aerospike</groupId>
<artifactId>spring-data-aerospike</artifactId>
<version>2.4.0.RELEASE</version>
</dependency>

4)Aerospike server 172.17.0.2:3000

**Comment by vikas8910** [comment]
> configuration

I am using docker image of aerospike. Below are the details,

1) Repository class code : 

@Repository
public interface BankDetailsRepository extends CrudRepository<BankMaster,String> {
    BankMaster findByBankName(String bankName);
    BankMaster findByCity(String city);
    List<BankMaster> findByLastname(String lastname);
    long countByCity(String city);
}

2) Model class code :

@AllArgsConstructor
@Data
public class BankMaster {

    @Id
    private String bankId;

    private String bankName;

    private String city;

    private String lastname;


}

3) implementation class code from where getting errors :

Iterable<BankMaster> findAll = bankDetailsRepository.findAll();
log.info("data1:{}",findAll);

BankMaster data1 = bankDetailsRepository.findByCity("mumbai");
log.info("findByCity:{}",data1);        

List<BankMaster> findByLastname = bankDetailsRepository.findByLastname("ioo");
log.info("findByBankName",findByLastname);

String bankName = "KOTAK BANK OF MANHINDRA";
og.info("findByBankName",bankDetailsRepository.findByBankName(bankName));

4) C Client Version 4.6.17

Aerospike Query Client Version 5.0.1

dependency in pom.xml

com.aerospike 
spring-data-aerospike 2.4.0.RELEASE
Aerospike server 172.17.0.2:3000

**Comment by vikas8910** [comment]
> please share your code - repository, configuration, document object and also the versions you'r using, if you can add the entire project as a GitHub project I'll be happy to review it.

I am using docker image of aerospike. Below are the details,

1) Repository class code : 

@Repository
public interface BankDetailsRepository extends CrudRepository<BankMaster,String> {
    BankMaster findByBankName(String bankName);
    BankMaster findByCity(String city);
    List<BankMaster> findByLastname(String lastname);
    long countByCity(String city);
}

2) Model class code :

@AllArgsConstructor
@Data
public class BankMaster {

    @Id
    private String bankId;

    private String bankName;

    private String city;

    private String lastname;


}

3) implementation class code from where getting errors :

Iterable<BankMaster> findAll = bankDetailsRepository.findAll();
log.info("data1:{}",findAll);

BankMaster data1 = bankDetailsRepository.findByCity("mumbai");
log.info("findByCity:{}",data1);        

List<BankMaster> findByLastname = bankDetailsRepository.findByLastname("ioo");
log.info("findByBankName",findByLastname);

String bankName = "KOTAK BANK OF MANHINDRA";
og.info("findByBankName",bankDetailsRepository.findByBankName(bankName));

4) C Client Version 4.6.17

Aerospike Query Client Version 5.0.1

dependency in pom.xml

com.aerospike 
spring-data-aerospike 2.4.0.RELEASE
Aerospike server 172.17.0.2:3000

**Comment by vikas8910** [comment]
I have also installed aerospike db on my local machine. But getting same type of error. What will be the reason behind that issue?

**Comment by roimenashe** [comment]
@vikas8910 Cloned your project and run some tests.
Everything execpt `countByCity(String city)` works fine for me, after I commented out the `findByCity` method definition and usages in both `BankDetailsRepository` and `FileStorageImpl` - this is the output I got:

> 2021-09-07 13:14:38.896  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : getBankDtls
2021-09-07 13:14:38.933  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : data:Optional[BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)]
2021-09-07 13:14:38.937  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : deleted lkaks:{}
2021-09-07 13:14:38.939  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findById lkaks:Optional.empty
2021-09-07 13:14:39.168  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : data1:[BankMaster(bankId=HDFC, bankName=HDFC, city=DELHI, lastname=JKJK), BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)]
2021-09-07 13:14:39.500  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findByCity:null
2021-09-07 13:14:39.805  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : result:[BankMaster(bankId=HDFC, bankName=HDFC, city=DELHI, lastname=JKJK), BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)]
2021-09-07 13:14:40.037  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findByBankName:BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)
2021-09-07 13:14:40.296  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findByBankName

* We are currently aware there is an issue with "countBy" query methods - we will look into it.

I used spring-data-aerospike `2.4.0.RELEASE` (same as yours) but with Aerospike server version: `Aerospike Community Edition build 5.5.0.7`, you didn't mention your server version so I just used what I had, I recommend that if its possible - upgrade both aerospike server and spring-data-aerospike to the latest - it contains a lot of bug fixes and improvements.

Also - you mentioned you are using aerospike query client 5.0.1, I don't see it in your pom.xml. Starting at `2.4.0.RELEASE` query mechanism is included in the spring-data-aerospike - you don't need to import anything else (https://github.com/aerospike-community/spring-data-aerospike/releases/tag/2.4.0.RELEASE).

**Comment by vikas8910** [comment]
> @vikas8910 Cloned your project and run some tests.
> Everything execpt `countByCity(String city)` works fine for me, after I commented out the `findByCity` method definition and usages in both `BankDetailsRepository` and `FileStorageImpl` - this is the output I got:
> 
> > 2021-09-07 13:14:38.896  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : getBankDtls
> > 2021-09-07 13:14:38.933  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : data:Optional[BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)]
> > 2021-09-07 13:14:38.937  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : deleted lkaks:{}
> > 2021-09-07 13:14:38.939  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findById lkaks:Optional.empty
> > 2021-09-07 13:14:39.168  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : data1:[BankMaster(bankId=HDFC, bankName=HDFC, city=DELHI, lastname=JKJK), BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)]
> > 2021-09-07 13:14:39.500  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findByCity:null
> > 2021-09-07 13:14:39.805  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : result:[BankMaster(bankId=HDFC, bankName=HDFC, city=DELHI, lastname=JKJK), BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)]
> > 2021-09-07 13:14:40.037  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findByBankName:BankMaster(bankId=SBI, bankName=SBI, city=MUMBAI, lastname=ASAS)
> > 2021-09-07 13:14:40.296  INFO 69133 --- [nio-8090-exec-2] d.f.service.FileStorageImpl              : findByBankName
> 
> * We are currently aware there is an issue with "countBy" query methods - we will look into it.
> 
> I used spring-data-aerospike `2.4.0.RELEASE` (same as yours) but with Aerospike server version: `Aerospike Community Edition build 5.5.0.7`, you didn't mention your server version so I just used what I had, I recommend that if its possible - upgrade both aerospike server and spring-data-aerospike to the latest - it contains a lot of bug fixes and improvements.
> 
> Also - you mentioned you are using aerospike query client 5.0.1, I don't see it in your pom.xml. Starting at `2.4.0.RELEASE` query mechanism is included in the spring-data-aerospike - you don't need to import anything else (https://github.com/aerospike-community/spring-data-aerospike/releases/tag/2.4.0.RELEASE).

Hi...aerospike query client 5.0.1 is  version of AQL which i have mentioned above and not server version... Also on my local machine i have installed aerospike-server-community-5.6.0.11-ubuntu20.04. But still i am getting the same error.

**Comment by roimenashe** [comment]
@vikas8910 Error 16 (Unsupported Server Feature) is coming from the Aerospike Server (Not spring-data-aerospike and not the Aerospike Java Client), you mentioned that you tried couple of server versions (5.6.0.11 locally and another one at the server with 172.17.0.2 IP address) and the error is reproducing in both, this error code is pretty generic and we need more details from the server's log in order to understand the problem better, I suggest point the aerospike.conf logging to a file (for example: `/var/log/aerospike/aerospike.log`) try to run the application and extract the logs from the aerospike.log file - once you have the detailed error logs please add it to this discussion and i'll review.

Couple of questions that might help:
1. How do you insert the bankMaster data to Aerospike?
2. How is the "C Client Version : 4.6.17" is relevant here? do you use it to store the data?
3. Are you using UDF's?
4. Do you store the user key?
* Also, if its possible please provide few records of data (select * from demo) - if the data is not sensitive of course.

**Comment by vikas8910** [comment]
1) How do you insert the bankMaster data to Aerospike? : 

select * from test.BankMaster;
+--------+-----------+----------+---------------------------------------------------+----------+----------+
| PK     | @user_key | city     | @_class                                           | bankName | lastname |
+--------+-----------+----------+---------------------------------------------------+----------+----------+
| "HDFC" | "HDFC"    | "DELHI"  | "io.demo.fileuploaddownload.model.BankMaster" | "HDFC"   | "JKJK"   |
| "SBI"  | "SBI"     | "MUMBAI" | "io.demo.fileuploaddownload.model.BankMaster" | "SBI"    | "ASAS"   |
+--------+-----------+----------+---------------------------------------------------+----------+----------+


2) How is the "C Client Version : 4.6.17" is relevant here? do you use it to store the data? : 
when i run aql command on terminal, then it shows below info:

$ aql
Seed:         127.0.0.1
User:         None
Config File:  /etc/aerospike/astools.conf /home/tech/.aerospike/astools.conf 
Aerospike Query Client
Version 5.2.0
C Client Version 5.2.0
Copyright 2012-2020 Aerospike. All rights reserved.
aql> 

3) Are you using UDF's? : NO

4) Do you store the user key? : No

5) records of data :

aql> select * from test;
+--------+-----------+----------+---------------------------------------------------+----------+----------+
| PK     | @user_key | city     | @_class                                           | bankName | lastname |
+--------+-----------+----------+---------------------------------------------------+----------+----------+
| "HDFC" | "HDFC"    | "DELHI"  | "io.demo.fileuploaddownload.model.BankMaster" | "HDFC"   | "JKJK"   |
| "SBI"  | "SBI"     | "MUMBAI" | "io.demo.fileuploaddownload.model.BankMaster" | "SBI"    | "ASAS"   |
+--------+-----------+----------+---------------------------------------------------+----------+----------+
2 rows in set (0.136 secs)

OK

aql> 

6) aerospike.log file attached
[aerospike.log{](https://github.com/aerospike-community/spring-data-aerospike/files/7122408/aerospike.log)

**Comment by roimenashe** [comment]
@vikas8910 Starting at Aerospike Server 5.6.0.3 - 
"[AER-6408] - (SCAN) Removed support for non partition-based basic scans, and deprecated scan options."
According to the release notes of Aerospike Server:
https://download.aerospike.com/download/server/notes.html

Thats why you are seeing all these warning messages: "WARNING (scan): (scan.c:681) basic scan got unsupported old scan options"

Please try any Aerospike Server below 5.6.0.3 or even a better solution (if its possible) - upgrade Spring Data Aerospike to latest (which includes a new Aerospike Java Client as well) and it should work.

**Comment by vikas8910** [comment]
> @vikas8910 Starting at Aerospike Server 5.6.0.3 -
> "[AER-6408](https://aerospike.atlassian.net/browse/AER-6408) - (SCAN) Removed support for non partition-based basic scans, and deprecated scan options."
> According to the release notes of Aerospike Server:
> https://download.aerospike.com/download/server/notes.html
> 
> Thats why you are seeing all these warning messages: "WARNING (scan): (scan.c:681) basic scan got unsupported old scan options"
> 
> Please try any Aerospike Server below 5.6.0.3 or even a better solution (if its possible) - upgrade Spring Data Aerospike to latest (which includes a new Aerospike Java Client as well) and it should work.

@roimenashe : Thanks for your help. I have changed version of Spring Data Aerospike from 2.4.0.RELEASE to 3.1.0 and its working.........really thanks for your support and help. :+1:
