### ISSUE TITLE
Map key serialization doesn't work with custom converter

### ISSUE THREAD

**Issue by raman-babich** [aerospike-community/spring-data-aerospike#312]
If you want to write entity
```java
@Data
@Document(collection = "collection")
public class Document {

    @Id
    String id;
    Map<SomeId, SomeEntity> entityMap;

}
```

to aerospike with custom converters for the SomeId, it will write SomeId keys with help of Object#toString() method, but the desired behavior is conversation to String using custom converter, in my opinion.

The problem is localized [here][1] and the possible solution is just to replace this line
```java
String simpleKey = key.toString();
```

with
```java
String simpleKey;
if (conversationService.canConvert(type.getComponentType(), String.class)) {
  simpleKey = conversionService.convert(key, String.class);
} else {
  simpleKey = key.toString();
}
```
What do you think about this?

[1]: https://github.com/aerospike-community/spring-data-aerospike/blob/3.2.0/src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java#L179

**Comment by roimenashe** [comment]
Hi @raman-babich,

If you have a custom converter on the `Document` class then you can simply convert the `SomeId` field (`Bin`) as you like. In this case the convertMap() method (that contains the code you suggested) won't be executed, the entire conversion logic will happen in [convertToAerospikeWriteData()](https://github.com/aerospike-community/spring-data-aerospike/blob/3.2.0/src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java#L68).

Here is an example of using a custom converter to add "prefix!" on each key in a map bin when persisting data into Aerospike and remove the "prefix!" when reading the data back from Aerospike:

Object:
```java
@Document
@Data
public static class MapWithKeyToConvert {
	@Id
	final long id;
	final Map<Object, String> mapWithDifferentKeyType;
}
```

Custom Converters:
```java
@WritingConverter
public static class MapWithKeyToConvertToAerospikeWriteDataConverter implements Converter<MapWithKeyToConvert, AerospikeWriteData> {

	@Override
	public AerospikeWriteData convert(MapWithKeyToConvert map) {
		Map<String, String> newConvertedMap = map.mapWithDifferentKeyType.entrySet().stream()
				.collect(Collectors.toMap(e -> "prefix!" + e.getKey().toString(), Map.Entry::getValue));

		Collection<Bin> bins = new ArrayList<>();
		bins.add(new Bin("mapWithDifferentKeyType", newConvertedMap));

		return new AerospikeWriteData(new Key("custom-namespace", "custom-set", Long.toString(map.id)), bins, 0, null);
	}
}

@ReadingConverter
public static class AerospikeReadDataToMapWithKeyToConvertConverter implements Converter<AerospikeReadData, MapWithKeyToConvert> {

	@Override
	@SuppressWarnings("unchecked")
	public MapWithKeyToConvert convert(AerospikeReadData source) {
		long id = Long.parseLong((String) source.getKey().userKey.getObject());
		Map<String, String> mapWithKeyToConvert = (Map<String, String>) source.getValue("mapWithDifferentKeyType");
		Map<Object, String> newConvertedReadMap = mapWithKeyToConvert.entrySet().stream()
				.collect(Collectors.toMap(e -> e.getKey().substring(e.getKey().indexOf("!") + 1), Map.Entry::getValue));
		return new MapWithKeyToConvert(id, newConvertedReadMap);
	}
}
```

Test:
```java
@Test
public void shouldWriteAndReadUsingCustomConverterMapKeys() {
	MappingAerospikeConverter converter =
			getMappingAerospikeConverter(new SampleClasses.MapWithKeyToConvertToAerospikeWriteDataConverter(), new SampleClasses.AerospikeReadDataToMapWithKeyToConvertConverter());

	AerospikeWriteData forWrite = AerospikeWriteData.forWrite(NAMESPACE);
	Map<Object, String> map = new HashMap<>();
	map.put("firstKey", "firstValue");
	map.put("secondKey", "secondValue");
	map.put("thirdKey", "thirdValue");

	Map<String, String> mapExpectedAfterConversion = map.entrySet().stream()
			.collect(Collectors.toMap(e -> "prefix!" + e.getKey().toString(), Map.Entry::getValue));

	SampleClasses.MapWithKeyToConvert mapWithKeyToConvert = new SampleClasses.MapWithKeyToConvert(999L, map);
	converter.write(mapWithKeyToConvert, forWrite);

	assertThat(forWrite.getKey()).consistsOf("custom-namespace", "custom-set", 999L);
	assertThat(forWrite.getBins()).containsOnly(new Bin("mapWithDifferentKeyType", mapExpectedAfterConversion));

	Map<String, Object> bins = of("mapWithDifferentKeyType", mapExpectedAfterConversion);
	SampleClasses.MapWithKeyToConvert read = converter.read(SampleClasses.MapWithKeyToConvert.class, AerospikeReadData.forRead(forWrite.getKey(), record(bins)));

	assertThat(read).isEqualTo(mapWithKeyToConvert);
}
```

If this doesn't help - please share a code example and more details about the provided SomeId type and the request results of what you are trying to accomplish.

Thanks!

**Comment by raman-babich** [comment]
Hi @roimenashe,

For example i have:
```java
@Data
@Document(collection = "collection")
public class Document {

    @Id
    String id;
    Map<SomeId, SomeEntity> entityMap;
}
```

```java
@Value
public class SomeId {

    String partA;
    String partB;
}
```

```java
@Value
public class SomeEntity {

    SomeId id;
    String fieldA;
    Long fieldB;
}
```

I don't have custom converter on `Document` class and i don't want to do it because I want to let spring-data-aerospike serialize instance of `Document` with minimal effort from me. I want to declare that instances of `SomeId` class should be serialized as `String` so that is why i make
```java
@WritingConverter
public class SomeIdToStringConverter implements Converter<SomeId, String> {

    @Override
    public String convert(SomeId id) {
        return id.getPartA() + "-" id.getPartB();
    }
}
```

and
```java
@ReadingConverter
public class StringToSomeIdConverter implements Converter<String, SomeId> {

    @Override
    public String convert(String id) {
        String[] parts = StringUtils.split(id,"-");
        return new SomeId(parts[0], parts[1]);
    }
}
```

after registering converters and saving some test instances of `Document` class i want to observe in the aerospike records like (for simplicity i will write it in the json but please assume that this is equivalent bin structure in the aerospike, a key of the record will have `_key` field name):
```json
{
  "_key": "someKey1",
  "entityMap": {
    "partA-partB1": {
      "id": "partA-partB1",
      "fieldA": "fieldA",
      "fieldB": 42
    },
    "partA-partB2": {
      "id": "partA-partB2",
      "fieldA": "fieldA",
      "fieldB": 42
    }
  }
}
```

but because converters will not be applied to the `entityMap` key the result will look like:
```json
{
  "_key": "someKey1",
  "entityMap": {
    "SomeId(partA=partA, partB=partB1)": {
      "id": "partA-partB1",
      "fieldA": "fieldA",
      "fieldB": 42
    },
    "SomeId(partA=partA, partB=partB2)": {
      "id": "partA-partB2",
      "fieldA": "fieldA",
      "fieldB": 42
    }
  }
}
```

**Comment by roimenashe** [comment]
@raman-babich 
Thanks for the detailed explanation, I see your point.
Opened a PR for this feature request (based on your example with few changes): https://github.com/aerospike-community/spring-data-aerospike/pull/313.

Once PR will be reviewed and hopefully merged this change will be included in the next version of Spring Data Aerospike.
Thanks you!

**Comment by roimenashe** [comment]
@raman-babich
Spring Data Aerospike 3.3.0 is out including support for custom conversions for map key.
You can see release notes at: https://github.com/aerospike-community/spring-data-aerospike/releases/tag/3.3.0.
It may take up to 24 hours for Maven Central to sync.
