### ISSUE TITLE
how to enable scans in aerospike

### ISSUE THREAD

**Issue by vikas8910** [aerospike-community/spring-data-aerospike#336]
i am using version of Spring Data Aerospike is 2.4.0.RELEASE and crud repository.

**Comment by roimenashe** [comment]
@vikas8910 
Hi, The same question was asked and answered on StackOverFlow,
https://stackoverflow.com/questions/70256714/how-to-enable-scansenabled-property-of-org-springframework-data-aerospike-conf

**Comment by vikas8910** [comment]
Thanks for your help :)
