### ISSUE TITLE
Mechanism similar to the Spring Data JPA Projections

### ISSUE THREAD

**Issue by bcherniakh** [aerospike-community/spring-data-aerospike#345]
Dear Spring Data Aerospike Team,

For the reasons of performance, it is sometimes needed to read only a part (some particular bins) of the document as not all the information from the document is required for the particular use-case, and it makes no sense to fetch all the details. It seems, that this goal cannot be achieved with the current implementation of Spring Data Aerospike. Technically it may be possible to imitate projections by creating a separate entity (Projection Entity) with a more narrow subset of fields compared to the main entity, mapping it to the same document, and creating a separate Repository. But this approach has significant downfalls.

1. It is not safe to create a separate Repository as it is possible to save the Projection Entity and lose some part of the information.
2. The current implementation of the [AerospikeTemplate#findById](https://github.com/aerospike-community/spring-data-aerospike/blob/f701aeb8c82b4c096e5ee1a839c6ce8249b7f661/src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java#L286) method does not pass the list of bins to the client. The same is true also for the [AerospikeTemplate#findAllByIds](https://github.com/aerospike-community/spring-data-aerospike/blob/f701aeb8c82b4c096e5ee1a839c6ce8249b7f661/src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java#L328). This means that all the bins for the given PK are fetched from the Aerospike anyway. 

Having all this said, it may be really helpful to have the mechanism similar to [projections](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/asciidoc/repository-projections.adoc) for the Aerospike implementation of the Spring Data. I believe that it is technically possible, as the client [has a way](https://javadoc.io/doc/com.aerospike/aerospike-client/latest/com/aerospike/client/AerospikeClient.html#get-com.aerospike.client.policy.BatchPolicy-com.aerospike.client.Key:A-java.lang.String...-) to retrieve the subset of bins for the given PK.

**Comment by roimenashe** [comment]
@bcherniakh Projection PR is now merged (https://github.com/aerospike-community/spring-data-aerospike/pull/415) and will be officially supported in the next release of Spring Data Aerospike (3.5.0) which we plan to release soon.
