### ISSUE TITLE
There seems to be a problem with the Mapping AerospikeWriteConverter.

### ISSUE THREAD

**Issue by park-taejoon** [aerospike-community/spring-data-aerospike#368]
Hello, I am using spring-data-aerospike well. Thank you.
I am a developer living in Korea.

I'm using a custom comverter.
    https://github.com/aerospike-community/spring-data-aerospike/blob/main/src/main/java/org/springframework/data/aerospike/convert/MappingAerospikeWriteConverter.java
![image](https://user-images.githubusercontent.com/33493333/162344761-65214f1b-0027-4eac-b2e3-f1519b17ac24.png)

converted Missing version.

https://github.com/aerospike-community/spring-data-aerospike/blob/main/src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeTemplate.java
![image](https://user-images.githubusercontent.com/33493333/162346539-86ce4171-e1db-44e7-a2e7-37efb2a84a1c.png)

entity.hasVersionProperty() is true

![image](https://user-images.githubusercontent.com/33493333/162345227-21a03a18-463e-4e43-8381-98909d1b3b5c.png)
https://github.com/aerospike-community/spring-data-aerospike/blob/main/src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java
Even if you inject the version, only RecordExistsAction.CREATE_ONLY....

Please fix the bug.

There are additional improvements I would like you to make.
Please improve RecordExistsAction so that it can be used in various ways depending on the version.
(RecordExistsAction.UPDATE is also available)

**Comment by roimenashe** [comment]
@park-taejoon 
In method `expectGenerationCasAwareSavePolicy`, if you have version greater than 0 for the given `AerospikeWriteData` it will use `RecordExistsAction.REPLACE_ONLY` which will replace the record only and fail if the record does not exist (not `CREATE_ONLY` as you mentioned).
If the `filter (v -> v > 0L)` didn't return a result then `.orElse` will be used and `RecoredExistsAction.CREATE_ONLY` which creates only and fails if record exists - will be selected

**Comment by roimenashe** [comment]
@park-taejoon
Closed for inactivity, if the previous answer is not satisfying please open a new ticket/contact us.
