### ISSUE TITLE
Rename this variable(record) to not match a restricted identifier.

### ISSUE THREAD

**Issue by ijusti** [aerospike-community/spring-data-aerospike#425]
There are a lot of `Record record` in a code. It will be incompatible with java 14+

**Comment by roimenashe** [comment]
@ijusti can you point me to a specific case?
All `Record record` that I'm aware of are `com.aerospike.client.Record` and not Java 14 `Record`.
At the moment the project successfully compiles and is compatible with Java 8.

**Comment by ijusti** [comment]
I mean future of lib

**Comment by reugn** [comment]
@ijusti This code smell doesn't break anything with Java 14 and above.

> Even if it is technically possible, Restricted Identifiers should not be used as identifiers. This is only possible for compatibility reasons, using it in Java code is confusing and should be avoided.
> Note that this applies to any version of Java, including the one where these identifiers are not yet restricted, to avoid future confusion.

But we'll open a PR to rename the `record` named vars to avoid confusion.
