### ISSUE TITLE
Support for Jakarta EE 9 is missing.

### ISSUE THREAD

**Issue by sachmuchsachin** [aerospike-community/spring-data-aerospike#464]
getting error - 
`java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @15eb5ee5`

while trying to use the latest version of sprind-data-aerospike (3.5.0) with spring boot 3x.

It seems the latest version of s-d-a doesn't yet support Jakarta EE9. is there a future plan for the same?
or is there a workaround?

**Comment by reugn** [comment]
@sachmuchsachin did you upgrade your Java version along with the migration or you're new to Spring Data Aerospike?

**Comment by sachmuchsachin** [comment]
I am upgrading to Java17 and Spring boot 3. from the compatibility matrix it seems boot 3 support is not yet available.

**Comment by reugn** [comment]
Yes, the Spring Boot 3 support is planned for the future release.
