### ISSUE TITLE
Support For CDT

### ISSUE THREAD

**Issue by JagjeetS** [aerospike-community/spring-data-aerospike#59]
I’m trying to run an example with Maps in maps, but the library version didn’t include com.aerospike.client.cdt.CTX;

So I upgraded from 1.0.2 to
compile('com.aerospike:spring-data-aerospike:2.2.0.RELEASE')
But now I get
Caused by: java.lang.ClassNotFoundException: org.springframework.data.mapping.MappingException
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_232]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_232]
... 69 common frames omitted

**Comment by Aloren** [comment]
> I’m trying to run an example with Maps in maps

In case you want to run tests of `spring-data-aerospike` -- all of them can be run on your local machine, the only requirement is having Docker installed and running.

> the library version didn’t include com.aerospike.client.cdt.CTX;

You are currently referring to `aerospike-client` imports. `aerospike-client` is transitive dependency of `spring-data-aerospike`, if you need to use later version of `aerospike-client` -- you need to specify that in your project's dependency management. Refer to: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management or https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html

> So I upgraded from 1.0.2 to compile('com.aerospike:spring-data-aerospike:2.2.0.RELEASE')

`2.2.0.RELEASE` is based on the `spring-data-commons` `2.2.0.RELEASE` (equal versions number is just a coincidence) to support Spring Boot 2.2. Make sure you are having up to date dependencies in your classpath.
