### ISSUE TITLE
save method doesn't return document version

### ISSUE THREAD

**Issue by KarpenkoAlexander** [aerospike-community/spring-data-aerospike#72]
When method save is invoked on repository parameterized with versioned document it's expected that returned document will contain not null versioned field.

Class SimpleAerospikeRepository contains following:
	
      @Override
	public <S extends T> S save(S entity) {
		Assert.notNull(entity, "Cannot save NULL entity");

		operations.save(entity);
		return entity;                            <-- **returns not saved entity**  
	}

**Comment by Aloren** [comment]
Version is set on the same `entity`, so the code is correct.
Please take a look at the following test: https://github.com/aerospike-community/spring-data-aerospike/blob/master/src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateSaveTests.java#L56
It validates the flow you're talking about. Can you please share your test case?

**Comment by KarpenkoAlexander** [comment]
In test you use object of sample VersionedClass. But definition of class containes version field as primitive. not an object. Consequently when you instantiate this object with constructor new VersionedClass(id, "foo") this field has default value equal to 0. In my document I have version field as Long (don't ask why, I'll review this decision), so when save is called this field is set to null.
