### ISSUE TITLE
Cache connected to namespace instead of set

### ISSUE THREAD

**Issue by barlog-m** [aerospike-community/spring-data-aerospike#83]
Could anyone please explain to me why a cache connected to a namespace instead of a set?

In according to documentation "Namespaces are like tablespaces for traditional SQL databases."
Nobody split collection in RDBMS by tablespaces, everyone splits by tables.

Or is this a special restriction to have only two caches for two different types?

**Comment by Aloren** [comment]
I agree that using set name for caching is more reasonable than namespace. Current implementation may be not quite correct, but it might be used by someone, so if you are willing to contribute the change needs to be backward compatible with current implementation.
