### ISSUE TITLE
Support for Async

### ISSUE THREAD

**Issue by DanCNo** [aerospike-community/spring-data-aerospike#99]
Is there support for asynchronous operations for the repository?

**Comment by Aloren** [comment]
Yes. You can use `ReactiveCrudRepository` and `ReactiveAerospikeOperations`.
https://github.com/aerospike-community/spring-data-aerospike/blob/master/src/main/java/org/springframework/data/aerospike/repository/ReactiveAerospikeRepository.java
https://github.com/aerospike-community/spring-data-aerospike/blob/master/src/main/java/org/springframework/data/aerospike/core/ReactiveAerospikeOperations.java
